### ISSUE TITLE
fig6a segfault

### ISSUE THREAD

**Issue by saarthdeshpande** [AIFM-sys/AIFM#17]
Executing run.sh in each subdirectory of aifm/exp/fig6a/ throws a segmentation fault. 

For linux_mem, execution is error-free only when kNumMutatorThreads = 1. For all other values of kNumMutatorThreads, a segmentation fault occurs. 

There is no other error message printed. How can I fix this?

Execution is on cloudlab using the profile provided in this repository.

**Comment by saarthdeshpande** [comment]
All variants throw a segmentation fault, but generate log files nonetheless. However, the results are not accurate for smaller loads. (attaching a comparison)

What `ip_addr:port` do I pass as `argv[2]` when running gdb main?

![IMG_0785](https://user-images.githubusercontent.com/42336020/221660910-c538a69e-73c9-4538-8fd7-22df4bb78c97.JPG)

**Comment by zainryan** [comment]
oh okay, it's a benigh/intentional segfault as the experiment script just forcibly kill the process once it gets the result; in other words, you're safe to ignore it once you get the result log. In terms of result discrepency, are you using exactly the original parameters when running the experiment? You mentioned something like small input in your initial post?

**Comment by saarthdeshpande** [comment]
Oh okay, great.
Yes, I'm using the original parameters. I mentioned small input because the seg fault is thrown only when `kNumMutatorThreads` > 1

**Comment by zainryan** [comment]
I believe the results are the same if you use the same yaxis scale with my figure

**Comment by saarthdeshpande** [comment]
Could you please share what conversion rate you use for cycles to microseconds?

**Comment by saarthdeshpande** [comment]
Thanks! I converted the cycles to microseconds as mentioned in the paper (2.4 GHz clock speed, 10 cores). The results match except for the last datapoint

![image](https://user-images.githubusercontent.com/42336020/221743132-fd3f1917-f6fe-4073-a9d3-946d403f9934.png)

**Comment by zainryan** [comment]
great, it's normal if you see slight differences across runs as there can be many sources of randomness.

**Comment by saarthdeshpande** [comment]
Great, thanks so much for your help! Closing this issue.
