### ISSUE TITLE
Zero window deadlock

### ISSUE THREAD

**Issue by YangZhou1997** [AIFM-sys/AIFM#3]
Hi, 

I was trying to stress testing the Shenango runtime associated with AIFM, and find that when sending objects larger than 64KB continuously, the TCP send function will cause deadlock. 

Then I see in tcp.c, there writing "/* TODO: must allow at least one byte to avoid zero window deadlock */"; just wonder if there is quick fix for this issue. 

Best,
Yang

**Comment by zainryan** [comment]
hi, try to apply this patch https://github.com/zainryan/serverless/commit/7cca43695514362cec81f1f35cc072b845774921

**Comment by YangZhou1997** [comment]
It works perfectly! Really appreciate your help!

**Comment by zainryan** [comment]
no problem :)
