### ISSUE TITLE
Link layer is not Ethernet.

### ISSUE THREAD

**Issue by vivian-jq** [AIFM-sys/AIFM#5]
Hello,

I am trying to run this project on our nodes. However, after building successfully by running `build_all.sh`,  it failed to run the tests with same error message in [issue #1](https://github.com/AIFM-sys/AIFM/issues/1).

After taking a deep look inside the system, we found that our failure was caused by a different link layer type `InfiniBand`, which asked to be `Ethernet` in dpdk dependency.

Can afim run on **infiniband network**? If can, how to adapt to it for us?

Here is our `ibv_devinfo`, hope it can help you.
```
hca_id: mlx5_0
        transport:                      InfiniBand (0)
        fw_ver:                         12.20.1820
        node_guid:                      248a:0703:00ad:3f7a
        sys_image_guid:                 248a:0703:00ad:3f7a
        vendor_id:                      0x02c9
        vendor_part_id:                 4115
        hw_ver:                         0x0
        board_id:                       DEL2180110032
        phys_port_cnt:                  1
                port:   1
                        state:                  PORT_ACTIVE (4)
                        max_mtu:                4096 (5)
                        active_mtu:             4096 (5)
                        sm_lid:                 4
                        port_lid:               16
                        port_lmc:               0x00
                        link_layer:             InfiniBand
```

**Comment by zainryan** [comment]
Hi, thanks for your interest! AIFM depends on [Shenango](https://github.com/abelay/shenango), an NSDI'19 work. Currently, Shenango only supports RoCE. The easiest way to reproduce the results is to follow our GitHub README and use the cloudlab machine.

**Comment by vivian-jq** [comment]
Fine, I got it. Thank you for your time!
