### ISSUE TITLE
failed to load ksched.ko

### ISSUE THREAD

**Issue by ckf104** [AIFM-sys/AIFM#9]
Hello, I am trying to reproduce results of this paper. I think I have run commends based on README.md, but some problems happened when I set `shenango`.
Here is output of my system.
```bash
$uname -a && ofed_info -s
Linux poweredge0-PowerEdge-R740 5.0.0-20-generic #21~18.04.1-Ubuntu SMP Thu Jun 27 04:04:37 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
MLNX_OFED_LINUX-4.6-1.0.1.1:
```
And `output.md` is the terminal output when I run `sudo ./build.sh` in `AIFM/shenango`.
Thanks in advance for any help.
[output.md](https://github.com/AIFM-sys/AIFM/files/7947876/output.md)

**Comment by zainryan** [comment]
Hi can you check if cstate is enabled in your kernel?

**Comment by ckf104** [comment]
Oh, I find `intel_idle.max_cstate=0` in the `grub` file of the server. I will change it into 5, reboot the server and try to set again.
Thanks for quick and kind response.

**Comment by zainryan** [comment]
You are very welcome. Feel free to reopen this issue if you still encounter the same error.
